### ISSUE TITLE
将验证框放入DialogFragment里面的问题

### ISSUE THREAD

**Issue by Geek-Spirit** [longer96/VerifyCode#1]
将验证框放入DialogFragment里面,大小不能自适应,无法显示全.

**Comment by longer96** [comment]
我可以加下你，看看具体情况吗？

**Comment by longer96** [comment]
![image](https://user-images.githubusercontent.com/20554776/70602321-19cb0e80-1c2f-11ea-9f9d-66fadb986daf.png)
我试了一哈没有找到问题诶

**Comment by Geek-Spirit** [comment]
2576674335 这个是我的Q,我是打算把这个控件放入我的dialog里面,然后发现这个控件只能设置固定大小,超出的部分不能显示.
